services:
  main: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: crunchbase:${CRUNCHBASE_VERSION:-latest}
    restart: always
    env_file:
      - .env
    networks:
      - default
    volumes:
      - ./:/app/src
